### ISSUE TITLE
Reasoner Architectural Refactor

### ISSUE THREAD

**Issue by jmsfltchr** [vaticle/typedb#6356]
## Problem to Solve

We want to achieve a cleaner architecture for the actors of the reasoner. Improving this cleanliness makes it faster to understand this complex domain and increases the ease with which we can add features.

Presently we find that the storyline is unclear and there are code smells, for example actors carrying 

Create a better storyline by better organising the logic of the actors of the reasoner. We should find that the whole architecture is far easier to understand and to work with. We want: a clearer separation between the processing of match and explain queries, 

## Proposed Solution

- [x] We realise that there is too much state held in many of resolvers. This state can be divided by the fixed variable bounds that are being processed. Over the course of these PRs we introduce a "bound" resolver as a complement to the retrievable, concludable and conclusion actors. These original actors become coordinators. In doing so we remove subsumption, which would otherwise cross actor boundaries. Subsumption was previously handled by the cache, which overcomplicated the cache significantly.
  - #6403
  - #6408
  - #6410
  - #6416
  - #6427
- [x] In order to find all facts, the reasoner was using an outer _reiteration_ to re-search all facts under certain conditions in case more answers could be derived. This process could often result in a linear increase in query latency, we believe a typical 2x slowdown for queries with rule cycles. Besides the performance impact, this method causes significant headaches in the code. It's an extra complexity that we would like to alleviate. In #6429 we introduce a new replacement feature, which detects when an infinite cycle has been blocked, and re-explores accordingly to find new facts that have become inferable. This PR addressed:
  - #6357 
  - #6278 
- [x] While working on #6429 we needed to add a significant feature to the `ResolutionTracer` to allow tracing in a fully parallel actor setting. This required all messages sent between actors to be traced. 
- [x] The model of the request tracing introduced was unsatisfactory in terms of traced requests vs. request factories. Pulling on this string we found that `RequestState` should not be tied to a request, but instead tracks the resolution of a particular state, now called `ResolutionState`. Not only this, but the `BoundConcludableResolver` in particular changes a lot, and becomes two actors, `Blocked` and `Exploring`. Both are used if the concludable is part of a cycle: #6448.
- [ ] #6453 partly addressed by https://github.com/vaticle/typedb/pull/6456
- [ ] #6451

We believe that we have found a better message passing model for the reasoner. If this model is successful then this work will be delayed due to being unnecessary or unhelpful:
- [ ] Create cache actors to address https://github.com/vaticle/typedb/issues/6450
- [ ] #6449 a precursor to cache actors.

**Comment by jmsfltchr** [comment]
Closed by https://github.com/vaticle/typedb/pull/6497 which built on these ideas but is a rewrite of the whole package!
