### ISSUE TITLE
Upgrade traversal engine

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb#6468]
## Problem to Solve

We will optimise the query traversal engine by incorporate sortedness properties. These properties can be used to eliminate generate-and-check closure operations we perform. 

## Proposed Solution

Utilise sortedness properties to optimise closure operations. By using sortedness, we can implement an efficient iterator intersection between 2 to N iterators. By doing so, we can eliminate closures and just use an intersection to generate "closed" ie. matching vertices in the traversal execution.

We should achieve the following by the end of this feature:
- significantly faster read queries
- eliminate specialised `RelationTraversal` that reasoner uses, which becomes a special case of the normal traversal engine
- traversal engine should natively implemented sortedness properties (even if we don't utilise them yet). Difficulties to enable them globally: disjunctions and reasoning

### Work Items

- [x] All adjacencies can return sorted iterators
- [x] Implement forward and backward sorted iterators
- [x] Update query planning to generate a minimal ordered spanning tree, along with a heuristic step to choose multiple good starting points (which may come from user-indicated sortedness, or concepts with fixed identifiers)
- [x] Update the traversal engine to follow the plan and execute all remaining edges as part of the iterator intersections
- [x] [Implement sorted match query natively in the traversal](https://github.com/vaticle/typedb/issues/6572)

## Additional Information

We should think ahead one step and consider native transitivity functionality in the traversal engine, and how it plays into the sortedness properties required.
  => **outcome**: we won't think about this yet, since it doesn't actually affect many users, and is difficult to solve within the sortedness constraints

**Comment by dmitrii-ubskii** [comment]
Resolved by #6546
